<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdca95e70e4957e5cfbc84e17edca3d84
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'StMartin\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'StMartin\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdca95e70e4957e5cfbc84e17edca3d84::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdca95e70e4957e5cfbc84e17edca3d84::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitdca95e70e4957e5cfbc84e17edca3d84::$classMap;

        }, null, ClassLoader::class);
    }
}
